# Generated by Django 3.1 on 2020-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.idfood.co.uk/wp-content/plugins/woocommerce/assets/images/placeholder.png', max_length=500, null=True),
        ),
    ]
